import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 * The Controller class is responsible for handling user interactions
 * with a calculator interface, responding to button clicks and triggering
 * appropriate actions in the associated CalculatorModel.
 *
 * This class implements the Java ActionListener interface to capture
 * ActionEvents generated by buttons in the calculator interface.
 *
 */
public class Controller implements ActionListener {
  private final Model model;

  /**
   * Constructs a new Controller instance.
   *
   * @param viewer The viewer component of the calculator interface.
   */
  Controller(Viewer viewer) {
    model = new Model(viewer);
  }


  /**
   * Handles user interactions by responding to ActionEvents generated
   * by buttons in the calculator interface.
   *
   * @param event The ActionEvent triggered by a button click.
   */
  @Override
  public void actionPerformed(ActionEvent event) {
    String command = event.getActionCommand();
    model.doAction(command);
  }
}
